// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLS81YEjTDsQf4iBb45YqtKJozbgfahA',
    appId: '1:642935907595:web:d84f89998287e8aa192e0e',
    messagingSenderId: '642935907595',
    projectId: 'perjadin-kpu',
    authDomain: 'perjadin-kpu.firebaseapp.com',
    storageBucket: 'perjadin-kpu.firebasestorage.app',
    measurementId: 'G-S0CYHL9MR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbKTyknbILx62j5q3nwhyqZ5VGI7cELVk',
    appId: '1:642935907595:android:61df730b67dff17f192e0e',
    messagingSenderId: '642935907595',
    projectId: 'perjadin-kpu',
    storageBucket: 'perjadin-kpu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSQI72jzjRhZKQFrU_htxf0G3Q2I1humw',
    appId: '1:642935907595:ios:ee147f130f8d670f192e0e',
    messagingSenderId: '642935907595',
    projectId: 'perjadin-kpu',
    storageBucket: 'perjadin-kpu.firebasestorage.app',
    iosBundleId: 'com.perjadin.kpu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSQI72jzjRhZKQFrU_htxf0G3Q2I1humw',
    appId: '1:642935907595:ios:ee147f130f8d670f192e0e',
    messagingSenderId: '642935907595',
    projectId: 'perjadin-kpu',
    storageBucket: 'perjadin-kpu.firebasestorage.app',
    iosBundleId: 'com.perjadin.kpu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLS81YEjTDsQf4iBb45YqtKJozbgfahA',
    appId: '1:642935907595:web:9f35300aed66bca0192e0e',
    messagingSenderId: '642935907595',
    projectId: 'perjadin-kpu',
    authDomain: 'perjadin-kpu.firebaseapp.com',
    storageBucket: 'perjadin-kpu.firebasestorage.app',
    measurementId: 'G-BKZ2S9YRV0',
  );
}
